/** Events barrel — structured debug logging seam + CLI wire protocol. */
export {
  DEBUG_LOG_PREFIX,
  debugLog,
  isPipelineDebugEnabled,
  PIPELINE_DEBUG_ENV_VAR,
  type DebugLogFields,
  type DebugLogFieldValue,
  type DebugLogOptions,
} from "./debug-log.js";

export {
  createPipelineEventEmitter,
  PipelineEventError,
  serializePipelineEvent,
  type CreatePipelineEventEmitterOptions,
  type PipelineBudgetScope,
  type PipelineBudgetDecisionEvent,
  type PipelineCliEvent,
  type PipelineCliEventBase,
  type PipelineCliEventFields,
  type PipelineCliEventOf,
  type PipelineCliEventType,
  type PipelineErrorEvent,
  type PipelineEventEmitter,
  type PipelineEventErrorCode,
  type PipelineEventSink,
  type PipelineEvidenceFinishedEvent,
  type PipelineGateDecisionEvent,
  type PipelineMergeDecisionEvent,
  type PipelinePrOpenedEvent,
  type PipelineProgressEvent,
  type PipelineResultEvent,
  type PipelineRunStartedEvent,
  type PipelineStageFinishedEvent,
  type PipelineStageStartedEvent,
} from "./pipeline-event.js";
